New function plot_with_gradient
GAA-UAM/scikit-fda pull request #272
Opened 2020-11-07 18:25 UTC by mellamansanchez

Used to plot a function with a gradient of colors depending of a list of values, e.g. depth

2020-11-07 18:38 UTC, vnmabus commented
I do not know why the diff reports everything as changed. Maybe you changed newlines to \r\n? Please, use only \n as the line separator.

2020-11-07 18:41 UTC, mellamansanchez commented
> I do not know why the diff reports everything as changed. Maybe you changed newlines to \r\n? Please, use only \n as the line separator.

I dont really know what could have happened I will review it, but I dont really understand what that change means.

2020-11-07 18:47 UTC, vnmabus commented
> 
> 
> > I do not know why the diff reports everything as changed. Maybe you changed newlines to \r\n? Please, use only \n as the line separator.
> 
> I dont really know what could have happened I will review it, but I dont really understand what that change means.

The convention for representing new lines is different in different domains and Operating Systems. Unix systems tend to use the character LF (line feed or '\n') to represent the end of a line, while Windows and some Internet protocols used CRLF (carriage return plus line feed or '\r\n'). This is usually configurable in your editor.

We use always the Unix convention, so please configure your editor to follow that.

2020-11-07 18:49 UTC, mellamansanchez commented
> > > I do not know why the diff reports everything as changed. Maybe you changed newlines to \r\n? Please, use only \n as the line separator.
> > 
> > 
> > I dont really know what could have happened I will review it, but I dont really understand what that change means.
> 
> The convention for representing new lines is different in different domains and Operating Systems. Unix systems tend to use the character LF (line feed or '\n') to represent the end of a line, while Windows and some Internet protocols used CRLF (carriage return plus line feed or '\r\n'). This is usually configurable in your editor.
> 
> We use always the Unix convention, so please configure your editor to follow that.

Ok thanks, I will review it.

2020-11-10 15:38 UTC, vnmabus requested changes

2020-11-10 15:38 UTC, vnmabus commented on skfda/exploratory/visualization/representation.py
> -        else:
Please configure your editor to remove trailing whitespace.

2020-11-10 15:38 UTC, vnmabus commented on skfda/exploratory/visualization/representation.py
> +    Plots each coordinate separately. If the domain is one dimensional, the
This has been changed in the develop branch, and the changes should not be reverted.

2020-11-10 15:38 UTC, vnmabus commented on skfda/exploratory/visualization/representation.py
> -
Why are you removing blank lines?

2020-11-10 15:38 UTC, vnmabus commented on skfda/exploratory/visualization/representation.py
> +def dd_plot(fdata, dist1, dist2, depth_method, chart=None, *, fig=None,
This functionality belong to a separate PR.

2020-11-10 15:38 UTC, vnmabus commented on skfda/exploratory/visualization/representation.py
> +def plot_with_gradient(fdata, chart=None, *, fig=None, axes=None,
We will try to follow the scikit-learn visualization API, with *Display objects and class methods to create them.

2020-11-15 23:13 UTC, closed without merging