Score functions for FData
GAA-UAM/scikit-fda pull request #429
Opened 2022-03-04 01:06 UTC by ElenaPetrunina

Close #378

2022-03-10 16:09 UTC, vnmabus requested changes

2022-03-11 16:00 UTC, ElenaPetrunina commented on skfda/misc/__init__.py
> +    score_functions,
Rename the file?

2022-03-12 08:48 UTC, vnmabus commented on skfda/misc/__init__.py
> +    score_functions,
Yes

2022-04-02 18:56 UTC, vnmabus requested changes

2022-04-02 18:56 UTC, vnmabus commented on skfda/misc/scoring.py
> +    return np.mean(integral[0]) / (end - start)
Probably this should be a function, as it is common between the different scores. Also, why not `_domain_measure` here?

2022-05-12 16:03 UTC, vnmabus commented
It appears that the topic of constant predictions has been already discussed in scikit-learn:
https://github.com/scikit-learn/scikit-learn/issues/16857

We should probably try to adapt the same solution as them, either in this PR or in a future fix before the next release: 
https://github.com/scikit-learn/scikit-learn/pull/17266

2022-10-09 20:32 UTC, merged