Error sphinx windows
GAA-UAM/scikit-fda pull request #477
Opened 2022-09-26 21:59 UTC by pedrog99

2022-09-27 15:08 UTC, vnmabus requested changes

2022-09-27 15:08 UTC, vnmabus commented on skfda/representation/_functional_data.py
> +            * False: negative values in `indices` indicate positional
This is wrongly represented as an additional parent in the generated documentation.

2022-09-27 16:05 UTC, pedrog99 commented on skfda/preprocessing/feature_construction/_function_transformers.py
> +        [ 0.73041066],
In Windows 10, I got unindentation Sphinx error with the previous format.

2022-09-28 11:55 UTC, vnmabus requested changes

2022-09-28 11:55 UTC, vnmabus commented on conftest.py
> +"""
This is still a string instead of a comment (use `#`).

2022-09-28 11:55 UTC, vnmabus commented on conftest.py
> +        and sys.platform.startswith('win')):
```suggestion
if (
    sys.version_info[0] == 3 and sys.version_info[1] >= 8
    and sys.platform.startswith('win')
):
```
Try to follow our style guide if possible.

2022-09-29 07:36 UTC, vnmabus approved these changes
LGTM

2022-09-29 07:37 UTC, merged