Feature/irregular_structure_and_operations
GAA-UAM/scikit-fda pull request #536
Opened 2023-04-27 14:41 UTC by opintosant

Full functionality of FDataIrregular structure and operations. Includes:

- Base structure. Create FDataIrregular. Load from FDataGrid or pandas.DataFrame.
- Representation: Plot and Scatter.
- Dataset 'bone_density_ext' added to _real_datasets.
- Arithmetic and numerical operations with scalars, vectors, and other FDataIrregular objects.
- Conversion from FDataIrregular to FDataGrid and FDataBasis.

2023-07-09 20:37 UTC, vnmabus requested changes
Sorry for the delay in reviewing this PR. It was very big, and an important piece of architecture, and I did not want to do a poor review of it.

I have to say that it is an impressive PR, moreover taking into account that you received almost no previous feedback on the code. The code is well written and documented. It follows good practices and it is usually not hard to follow. I think it will be a great addition to the package once some (minor) issues are fixed.

I think it would have been good to test also Pandas compatibility, given that you made the effort of following Pandas API. However this is not necessary right now. You already did a great job and this PR is already very big. I also do not want to force you to expend additional time with this.

Please, answer the questions that I raised, and if you want and have time try to improve the code using the review comments. If you are unable or unwilling to, please tell me, so I can do the finishing touches by myself.

2023-07-09 20:37 UTC, vnmabus commented on skfda/tests/test_irregular_operations.py
> +random_state = np.random.RandomState(seed=SEED)
Maybe we should use [`default_rng`](https://numpy.org/doc/stable/reference/random/generator.html) instead if possible, which uses a `Generator`, the modern alternative to `RandomState`.

2023-10-12 08:55 UTC, pcuestas reviewed
I tried my best to resolve the review changes and comments from @vnmabus's review. I added some questions to the comments I did not understand or that I have doubts about.

2023-10-12 08:55 UTC, pcuestas commented on skfda/representation/irregular.py
> +    dim_ranges = []
I rewrote it. I hope it is clearer now.

2023-10-12 08:55 UTC, pcuestas commented on skfda/representation/irregular.py
> +    ranges = []
Done.

2023-10-12 08:55 UTC, pcuestas commented on skfda/representation/irregular.py
> +        """Create a FDataIrregular object from a pandas dataframe.
I guess the suggestion is to consider removing the `from_dataframe()` method altogether, right? I think we should discuss this in the next meeting.

2023-10-12 08:55 UTC, pcuestas commented on skfda/representation/irregular.py
> +    def from_datagrid(
I think `from_fdatagrid` is clearer by being more explicit.

2023-10-12 08:55 UTC, pcuestas commented on skfda/representation/irregular.py
> +        from itertools import product
https://github.com/GAA-UAM/scikit-fda/blob/8a6dd5deedb1de3b1154202cbcb54603580c5b99/skfda/representation/irregular.py#L368-L374

Do you mean that the use of `itertool.product` can/should be avoided?
Or that the declaration of `grid_point_indexes` could be improved (in particular, line 370 from previous code snippet)?

2023-10-13 13:10 UTC, vnmabus commented on skfda/representation/irregular.py
> +        sorted_arguments, sorted_values = self._sort_by_arguments()
Fair enough.

2023-10-14 21:37 UTC, vnmabus commented on skfda/representation/irregular.py
> +    def indices_start_end(self) -> Sequence[Tuple[int, int]]:
No me convence este método. Creo que es innecesario existiendo `np.split`, `np.bincount` y `ufunc.reduceat`. Además, en cualquier caso no debería ser público.

2023-10-16 09:00 UTC, pcuestas commented on skfda/representation/irregular.py
> +        argument_columns: Sequence[str | None],
I think you suggested the change: https://github.com/GAA-UAM/scikit-fda/pull/536#discussion_r1239994303

2023-10-16 09:06 UTC, vnmabus commented on skfda/representation/irregular.py
> +        argument_columns: Sequence[str | None],
My bad, I thought this was the `__init__` method. Yes, in this context it should not be used, I was right the first time.

2023-10-16 09:17 UTC, pcuestas commented on skfda/representation/irregular.py
> +    def indices_start_end(self) -> Sequence[Tuple[int, int]]:
Removed.

2023-10-17 19:59 UTC, pcuestas commented on skfda/representation/irregular.py
> +        from itertools import product
I rewrote this function. I believe it uses more memory now, but there are no python loops; only calls to numpy functions.

2024-03-11 11:44 UTC, vnmabus approved these changes
With the recent changes from PR #593, this is now ready to go,

2024-03-11 11:44 UTC, merged