Feature/fdm
GAA-UAM/scikit-fda pull request #621
Opened 2024-07-09 17:01 UTC by E105D104U125

- Added FDM feature in the dimensionality reduction submodule of the preprocessing module `_fdm.py` .
- Included a test file for testing the new method `test_fdm.py` .
- Created and added an example for the wiki `plot_fdm.py` .

2024-07-09 17:16 UTC, E105D104U125 commented
Ignoring flake8 errors WPS440 and WPS441 in the doc example file `plot_fdm` .

2025-03-09 13:07 UTC, vnmabus requested changes
Again, sorry for taking so long reviewing this. The main functionality is great, I just have a couple of nitpicks in documentation and tests.

If you do not have the time/will to do the changes, just tell me and I will apply them myself (but please, answer my question about the comparison in the tests, as I truly do not remember which was the reference package).

2025-03-09 13:07 UTC, vnmabus commented on skfda/tests/test_fdm.py
> +    """Compare the embedding in grid against the fda package."""
Does the fda package have FDM? I do not think so. Can you put the code used to get the values in the docstring?

2025-03-09 13:07 UTC, vnmabus commented on skfda/tests/test_fdm.py
> +def laplacian_kernel(fd: FData, sigma: float) -> NDArrayFloat:
This is unused, remove.

2025-03-09 15:45 UTC, E105D104U125 commented on skfda/preprocessing/dim_reduction/_fdm.py
> +    Notes:
I agree.

2025-03-09 15:50 UTC, E105D104U125 commented on skfda/tests/test_fdm.py
> +def rbf_kernel(fd: FData, sigma: float) -> NDArrayFloat:
Indeed. The fdm module was implemented before extending the covariance kernels to functional data. It makes no sense anymore, I'll change it.

2025-03-09 15:51 UTC, E105D104U125 commented on skfda/tests/test_fdm.py
> +    """Compare the embedding in grid against the fda package."""
These examples where computed by hand. I will the necessary details for reproducibility of the calculations.

2025-03-09 16:25 UTC, E105D104U125 commented
> Again, sorry for taking so long reviewing this. The main functionality is great, I just have a couple of nitpicks in documentation and tests.
> 
> If you do not have the time/will to do the changes, just tell me and I will apply them myself (but please, answer my question about the comparison in the tests, as I truly do not remember which was the reference package).

I implemented and pushed all changes.
There is a problem with the style tests `FileNotFoundError: [Errno 2] No such file or directory: 'examples/plot_fdm.py skfda/preprocessing/dim_reduction/__init__.py `.

2025-03-09 16:31 UTC, E105D104U125 commented
Also, I created a web version of the study that I did on the FDM method, [https://eduardoterres.github.io/Functional-Diffusion-Maps/](FDM GitHub pages).
I was thinking it could be interesting to reference it in the FDM class example of use. The website is essentially a more in depth version of the example of use notebook, including mathematical background and further experiments.

2025-03-09 17:22 UTC, vnmabus commented
> Also, I created a web version of the study that I did on the FDM method, [FDM GitHub pages](https://eduardoterres.github.io/Functional-Diffusion-Maps/) I was thinking it could be interesting to reference it in a note in the FDM class example of use. The website is essentially a more in depth version of the example of use notebook, including mathematical background and further experiments. Please let me know your view on this.

Hey, that is cool! Yes, you can add a note on the top pointing to that page, or just reference it with a footnote cite, also at the top of the page, so that nobody misses it.

2025-03-22 09:19 UTC, vnmabus commented on skfda/tests/test_fdm.py
> +    """Compare the embedding in grid against the fda package."""
I would then remove the mention to the "fda package". However, if we compared with the FDM implementation in the paper, and that implementation is publicly available (I do not remember if that was the case), then we can link to that.

2025-03-22 09:25 UTC, vnmabus commented on skfda/preprocessing/dim_reduction/_fdm.py
> +class FDM(
I forgot to mention that, but FDM is not a well-known acronym, such as PCA. In fact, FDM seems to be used for "Fast difussion models" of "Fuzzy difussion models" in the literature.  I propose to use `DiffusionMap` as the name, instead, given that the "functional" part is redundant, being in a functional data package.

2025-03-22 15:42 UTC, E105D104U125 commented
Thanks for the comments and suggestions. I will work on it in two weeks time, right now I'll be unable.

2025-03-22 15:43 UTC, vnmabus commented
Sure! Take the time you need.

2025-03-23 15:50 UTC, vnmabus commented
At the end I found some free time and did the changes myself, as they where small. Thanks again for your contribution, I wish you luck with your current endeavors!

2025-03-23 15:50 UTC, vnmabus approved these changes

2025-03-23 15:50 UTC, merged

2025-03-23 15:51 UTC, vnmabus commented
@all-contributors add @E105D104U125 for code, documentation, tests, examples and research.

2025-03-23 16:12 UTC, E105D104U125 commented
> At the end I found some free time and did the changes myself, as they where small. Thanks again for your contribution, I wish you luck with your current endeavors!

Thanks for finishing things up @vnmabus. I wish you luck too!